#!/usr/bin/env bash
#
# Compile + link verification for isolated-record WITHOUT a full OBS build.
#
# This is NOT the production build (use CMake + the OBS plugin template for a
# distributable, correctly-Qt-matched .plugin). It exists to catch source/API
# errors quickly by compiling against OBS source headers and linking against
# the OBS.app frameworks already installed on this machine.
#
# Prerequisites (macOS / Apple Silicon, Homebrew):
#   brew install simde qtbase
#   git clone --depth 1 --branch <OBS_VERSION> https://github.com/obsproject/obs-studio.git ../obs-studio-src
#   (OBS_VERSION must match /Applications/OBS.app — check its Info.plist)
#
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)

OBS_SRC="${OBS_SRC:-$ROOT/obs-studio-src}"
QT="${QT:-/opt/homebrew/Cellar/qtbase/6.11.0}"
OBSF="${OBSF:-/Applications/OBS.app/Contents/Frameworks}"
MOC="$QT/share/qt/libexec/moc"

GEN="$HERE/.gen"
OUT="$HERE/build-verify"
mkdir -p "$GEN" "$OUT"

# obsconfig.h is normally generated by OBS's CMake; a minimal stub satisfies
# the header includes for a compile check.
cat > "$GEN/obsconfig.h" <<'EOF'
#pragma once
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
EOF

# version.h is normally produced by configure_file() in CMakeLists.txt.
cat > "$HERE/src/version.h" <<'EOF'
#pragma once
#define PROJECT_VERSION "0.1.2"
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 2
EOF

flags=(
  -std=c++20 -fPIC -Wall
  -I"$GEN"
  -I"$OBS_SRC/libobs"
  -I"$OBS_SRC/frontend/api"
  -I"$HERE/src"
  -I/opt/homebrew/include
  -I"$QT/lib/QtCore.framework/Headers"
  -I"$QT/lib/QtGui.framework/Headers"
  -I"$QT/lib/QtWidgets.framework/Headers"
  -F"$QT/lib"
)

echo "==> moc"
"$MOC" "$HERE/src/dock.hpp" -o "$OUT/moc_dock.cpp"

echo "==> compile"
objs=()
for f in plugin-main isolated-record recorder-api audio-recorder dock; do
  clang++ "${flags[@]}" -c "$HERE/src/$f.cpp" -o "$OUT/$f.o"
  objs+=("$OUT/$f.o")
done
clang++ "${flags[@]}" -c "$OUT/moc_dock.cpp" -o "$OUT/moc_dock.o"
objs+=("$OUT/moc_dock.o")

echo "==> link (bundle)"
# NOTE: link Qt frameworks by explicit binary path — clang dedupes a bare
# `-framework QtCore` here and drops it, leaving QtCore symbols undefined.
clang++ "${objs[@]}" \
  -bundle \
  -F"$OBSF" -framework libobs "$OBSF/libobs-frontend-api.1.dylib" \
  "$QT/lib/QtWidgets.framework/QtWidgets" \
  "$QT/lib/QtGui.framework/QtGui" \
  "$QT/lib/QtCore.framework/QtCore" \
  -o "$OUT/isolated-record.so"

echo "==> OK: $OUT/isolated-record.so"
nm -gU "$OUT/isolated-record.so" | grep -E "_obs_module_(load|unload|ver)$" || true
